test:
  service: Disk
  root: <%= Rails.root.join('tmp/storage') %>

yandex:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
  bucket: <%= Rails.application.credentials.dig(:aws, :bucket) %>
  endpoint: <%= Rails.application.credentials.dig(:aws, :endpoint) %>
  region: 'qq'
  # public: true
